### ISSUE TITLE
please support non-universal (possibly AOT) version of --mobile flag

### ISSUE THREAD

**Issue by born2net** [angular/mobile-toolkit#112]
I love the fact CLI will soon support back the ```--mobile``` however I really don't want to use angular universal.

It would be awesome if we can have a non universal (and possibly AOT) version of  seed cli PWA support,

thanks as always,

Sean

**Comment by born2net** [comment]
correct me if I am wrong but AOT is a better fit for PWA as they give us the smallest runtime, fastest load times and will make angular2 universal irrelevant...  ( traditionally you don't need SEO for apps )
 I am really trying to avoid angular universal and if we can have a pure nonuniversal version of this project it would be really helpful...

**Comment by gdi2290** [comment]
Universal was only used for generating the app-shell. The app-shell can be done manually like how it's done for polymer and in fact there are other ways to generate the app-shell. Using Universal for pre-rendering causes problems since for Universal we need to isolate state for each request/response. Universal requires applications to at least be testable for it to be universal compatible since the idea is to swap out services using di. For generating the app-shell using the browser is probably the best bet since developers can write any type of code and not worry about rendering fast

**Comment by born2net** [comment]
gdi2290 are you aware of any angular2 seed project for PWA without universal, just a quick starter with material 2?

regards

**Comment by gdi2290** [comment]
https://github.com/webmaxru/pwa-guide-ngpoland/tree/step-dashboard

**Comment by webmaxru** [comment]
@gdi2290, thanks for mentioning this repo here. @born2net, please notice - this is not a seed or starter, but more just a proof-of-concept: Mobile Toolkit is possible to experiment with right now (at least some parts of it) and (as a side effect) Angular Material 2 is possible to use with Angular Universal (some components).

**Comment by born2net** [comment]
tx guys for the comments.
@webmaxru what would it take to remove universal from your project... ?
As I am trying to get away from using universal with my pwa

regards

Sean

FYI @webmaxru 
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by webmaxru** [comment]
@born2net: just run `gulp build-noshell` instead of regular `build` - Universal will not be invoked, but of course you will loose the great possibility to feed totally rendered (incl. inline styles) app shell to the browser (to start paining something meaningful even before JS loaded).

**Comment by born2net** [comment]
got it, TX!
